version: '2'

services:

### MariaDB Database Server ############################################

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - mariadb_data:/bitnami

### TesLink Report Server ###############################################

  testlink:
    image: bitnami/testlink:latest
    ports:
      - 8008:80
      - 443:443
    volumes:
      - testlink_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=verysecretadminpassword
      - TESTLINK_EMAIL=admin@example.com

### Jenkins CI Server ##################################################

  jenkins:
      build: ./jenkins
      environment:
        JAVA_OPTS: "-Djava.awt.headless=true -Xmx1024m -XX:MaxPermSize=512m"
      ports:
        - 50000:50000
        - 8088:8080
      privileged: true
      volumes:
        - ./phpunit-reporter:/var/jenkins_home/phpunit-reporter
        - jenkins_data:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock


### SMTP Server #########################################################

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

### Named Volumes ########################################################

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  jenkins_data:
    driver: local
